version: '3.7'

services:
  node:
    image: redis:6.0-alpine
    networks: 
      - redis
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - ./start_redis.sh:/start_redis.sh
      - data:/data
    init: true
    command: sh /start_redis.sh


networks:
  redis:

volumes:
  data:
